version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg16
    container_name: quickdesk-postgres-pgvector
    restart: always
    environment:
      POSTGRES_DB: quickdesk
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:  
      - postgres_data:/var/lib/postgresql/data
      - ./setup-pgvector.sql:/docker-entrypoint-initdb.d/setup-pgvector.sql
    networks:
      - quickdesk-network

  admin:
    image: adminer
    container_name: quickdesk-adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - quickdesk-network

volumes:
  postgres_data:

networks:
  quickdesk-network:
    driver: bridge
